myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", views.register, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path('student/', include('student.urls')),
    path('planner/', include('planner.urls')),
    path("", views.Homepage, name="homepage"),

]

planner/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from myproject import settings
from django.conf.urls.static import static

app_name = 'planner'

urlpatterns = [
    
    path('subjectall', views.planner_subjectall, name='subjectall'),
    path('planning', views.planner_planning, name='planning'),
    path('plan-form', views.planner_form, name='plan-form'),
    path('gradepredic', views.gradepredic, name='gradepredic'),
    url(r'^insert/(?P<username>\w+)/$', views.insert, name='insert'),
    #url(r'insert$', views.insert, name='insert'),
    url(r'inser_plan', views.inser_plan, name='inser_plan'),
    url(r'^create_plans/(?P<username>\w+)/(?P<plan_id>\w+)/$', views.create_plans, name='create_plans'),
    url(r'^delete_plan/(?P<username>\w+)/(?P<plan_id>\w+)/$', views.delete_plan, name='delete_plan'),
    url(r'^home/(?P<username>\w+)/$', views.home, name="home"),
   
]

student/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from myproject import settings
from django.conf.urls.static import static

app_name = 'student'

urlpatterns = [
    path('', views.Index, name='Index'),
    path('Planner', views.Planner, name='Planner'),
    path('Plannerco', views.Plannerco, name='Plannerco'),
    path('Planned', views.Planned, name='Planned'),
    path('History', views.SHistory, name ='History'),
    path('Profile', views.Profile, name='Profile'),
  
]

planner/models.py
from django.db import models
from student.models import Student
from django.urls import reverse


# Create your models here.


class Planner(models.Model):
    plan_id = models.IntegerField(primary_key=True)
    student_id = models.ForeignKey(
        Student, on_delete=models.CASCADE, default=None)
    plan_name = models.CharField(max_length=255, default=None)
    plan_year = models.IntegerField()
    plan_semester = models.IntegerField()
    plan_gps = models.FloatField()
    plan_no = models.IntegerField()
    plan_totalcredit = models.IntegerField()
    plan_remark = models.CharField(max_length=500)


class Category(models.Model):
    CategoryID = models.CharField(max_length=1)
    CategoryNAme = models.CharField(max_length=50)
    Category_credit = models.CharField(max_length=3)
    CreateTime = models.DateTimeField('date create')
    CreateBy = models.CharField(max_length=150)
    UpdateTime = models.DateTimeField('date update')
    UpdateBy = models.CharField(max_length=150)


class SubjectGroup(models.Model):
    SubjectGroupID = models.CharField(primary_key=True, max_length=2)
    SubjectGroupName = models.CharField(max_length=250)
    Credit = models.IntegerField()
    CreateTime = models.DateTimeField('date create')
    CreateBy = models.CharField(max_length=150)
    UpdateTime = models.DateTimeField('date update')
    UpdateBy = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None)

class Subject(models.Model):
    subject_id = models.CharField(primary_key=True, max_length=5)
    subject_code = models.CharField(max_length=8)
    subject_nameTH = models.CharField(max_length=100)
    subject_nameEN = models.CharField(max_length=100)
    #subject_detail = models.TextField(max_length=500, default=None)
    subject_credit = models.IntegerField()
    is_have_pre_subject = models.BooleanField(default=None)
    subjectgroup = models.ForeignKey(SubjectGroup, on_delete=models.CASCADE, default=None)

class PreSubject(models.Model):
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)
    pre_subject_id = models.IntegerField()

class SubjectActive(models.Model):
    SA_year = models.CharField(max_length=4)
    SA_semster = models.CharField(max_length=50)
    SA_id = models.CharField(max_length=8)
    SA_nameTH = models.CharField(max_length=100)
    SA_nameEN = models.CharField(max_length=100)
    SA_credit = models.CharField(max_length=1)
    SA_hour= models.CharField(max_length=1)

class addsubject(models.Model):
    subject = models.CharField(max_length=50)
    credit = models.CharField(max_length=1)
    addsubject_date = models.CharField(max_length=10)
    addsubject_startime = models.TimeField(auto_now=False, auto_now_add=False)
    addsubject_endtime = models.TimeField(auto_now=False, auto_now_add=False)
    #addsubject_hours = models.DurationField()
    #def get_time_diff(self):
         #addsubject_hours = addsubject_hours = addsubject_endtime - self.addsubject_startime
         #print (addsubject_hours)
         #return addsubject_hours


class plan(models.Model):
    plan = models.CharField(max_length=200)
    user_ID = models.CharField(max_length=200)

    def __str__(self):
        return "%s %s" % (self.plan, self.user_ID)

class Subject_plan(models.Model):
      Subject_ID = models.CharField(max_length=8,default=0)
      Subject_name = models.CharField(max_length=200)
      Subject_credit = models.IntegerField(default=0)
      group = models.IntegerField(default=0)

class Create_plan(models.Model):
      Subject_ID = models.ForeignKey(Subject_plan,on_delete=models.CASCADE, null=True, blank=True)
      plan_no = models.IntegerField(default=0)
      Time_start = models.TimeField(blank=True, null=True) 
      Time_close = models.TimeField(blank=True, null=True)
      day_id = models.IntegerField(default=0)
      Username = models.CharField(max_length=200,default=0)

    

student/models.py
from django.db import models
#from PIL import Image

class Student(models.Model):
    student_id = models.CharField(
        primary_key=True, max_length=10, default=None)
    student_name = models.CharField(max_length=100)
    student_surname = models.CharField(max_length=100)
    student_password = models.CharField(max_length=50)
    student_year = models.IntegerField()
    student_gpa = models.FloatField()
    student_email = models.EmailField(max_length=254)
    student_totalcredit = models.IntegerField()
    
    


class History(models.Model):
    studentid = models.CharField(max_length=10, default=None)
    Year = models.CharField(max_length=4,default=None)
    Semester =models.CharField(max_length=7, default=None)
    
    SubjectID1 =models.CharField(max_length=8, default=None)
    Subject1 =models.CharField(max_length=50, default=None)
    Grade1 = models.CharField(max_length=2,default=None)
    credit1 = models.CharField(max_length=1,default=3)
    
    SubjectID2 =models.CharField(max_length=8, default=None)
    Subject2 =models.CharField(max_length=50, default=None)
    Grade2 = models.CharField(max_length=2,default=None)
    credit2 = models.CharField(max_length=1,default=3)
    
    SubjectID3 =models.CharField(max_length=8, default=None)
    Subject3 =models.CharField(max_length=50, default=None)
    Grade3 = models.CharField(max_length=2,default=None)
    credit3 = models.CharField(max_length=1,default=3)
    
    SubjectID4 =models.CharField(max_length=8, default=None)
    Subject4 =models.CharField(max_length=50, default=None)
    Grade4 = models.CharField(max_length=2,default=None)
    credit4 = models.CharField(max_length=1,default=3)
    
    SubjectID5 =models.CharField(max_length=8, default=None)
    Subject5 =models.CharField(max_length=50, default=None)
    Grade5 = models.CharField(max_length=2,default=None)
    credit5 = models.CharField(max_length=1,default=3)
   
    SubjectID6 =models.CharField(max_length=8, default=None)
    Subject6 =models.CharField(max_length=50, default=None)
    Grade6 = models.CharField(max_length=2,default=None)
    credit6 = models.CharField(max_length=1,default=3)
    
    SubjectID7 =models.CharField(max_length=8, default=None)
    Subject7 =models.CharField(max_length=50, default=None)
    Grade7 = models.CharField(max_length=2,default=None)
    credit7 = models.CharField(max_length=1,default=3)
    
    SubjectID8 =models.CharField(max_length=8, default=None)
    Subject8 =models.CharField(max_length=50, default=None)
    Grade8 = models.CharField(max_length=2,default=None)
    credit8 = models.CharField(max_length=1,default=3)
    
    SubjectID9 =models.CharField(max_length=8, default=None)
    Subject9 =models.CharField(max_length=50, default=None)
    Grade9 = models.CharField(max_length=2,default=None)
    credit9 = models.CharField(max_length=1,default=3)
    
    SubjectID10 =models.CharField(max_length=8, default=None)
    Subject10 =models.CharField(max_length=50, default=None)
    Grade10 = models.CharField(max_length=2,default=None)
    credit10 = models.CharField(max_length=1,default=3)
    
    GPAX= models.CharField(max_length=4,default=None)
    GPA= models.CharField(max_length=4,default=None)
    

planner/forms.py
from django import forms
from .models import addsubject ,Planner 



class addsubject_form(forms.ModelForm):
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    credit = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    addsubject_date = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    addsubject_startime = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    addsubject_endtime = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    #addsubject_hours = forms.DurationField()
    
    class Meta:
        model = addsubject 
        fields = [
			'subject',
            'credit',
            'addsubject_date',
            'addsubject_startime',
			'addsubject_endtime', 
        ]

student/forms.py
from django import forms
from .models import Student ,History


class Profile_form(forms.ModelForm):
    student_id = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    student_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    student_surname = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    student_password = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    student_year = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    student_gpa = forms.FloatField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    student_email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    student_totalcredit = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    #image = forms.ImageField()
    class Meta:
        model = Student
        fields = [
            'student_id',
            'student_name',
            'student_surname',
            'student_password',
            'student_year',
            'student_gpa',
            'student_email',
            'student_totalcredit',
        ]
        
class History_form(forms.ModelForm):
    studentid = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    Year = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    Semester = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    SubjectID = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    Subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    Grade = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control',}))
    
    class Meta:
        model = History
        fields = [
            'studentid',
            'Year',
            'Semester',
            'SubjectID',
            'Grade',
            
        ]

planner/views.py
from django.shortcuts import render, redirect
from planner.models import Subject, SubjectGroup, PreSubject, Category,addsubject,Subject_plan
from student.models import History 
from .forms import addsubject_form
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from planner.models import plan
from planner.models import Subject_plan
from planner.models import Create_plan
from django.db.models import Sum
from django.db.models import Count

def planner_subjectall(request):
    s = Subject.objects.filter()
    sg = SubjectGroup.objects.filter()
    ps = PreSubject.objects.filter()
    c = Category.objects.filter()

    context = {
        's': s,
        'sg': sg,
        'ps': ps,
        'c': c
    }

    return render(request, 'planners/planner/planner_subjectall.html', context)
    

def planner_planning(request):
    add_sj = addsubject.objects.filter()
    context ={
        'add_sj' : add_sj
    }
    return render(request, 'planners/planner/planner_planning.html', context)


@login_required 
def planner_form(request):
    P = addsubject.objects.filter()
    form = addsubject_form()
    context = {
                
                'form' : form,
                'P' : P  
            }
    if request.method == 'POST':
        form = addsubject_form(request.POST, request.FILES)
        
        if form.is_valid():
            user_pr = form.save(commit=False)
            user_pr.save()
            messages.success(request, f"เพิ่มวิชาเรียบร้อยแล้ว")
            return render(request, 'planners/planner/planner_form.html', {'form': form, 'user_pr': user_pr})
    else:
        print('no post')
            
    return render(request, 'planners/planner/planner_form.html',context)

def gradepredic(request):
    Ss = Subject_plan.objects.filter()
    H = History.objects.filter(studentid=request.user).values()
    context = {
                
                'Ss' : Ss,
                'H' : H  
            }
    return render(request, 'planners/planner/grade_predic.html',context)
    


#**************************************************************************************
def home(request,username):
    data = plan.objects.filter(user_ID = username)
    if not data :
        return render(request, 'planners/planner/home.html')
    else:
        return render(request, 'planners/planner/home.html',{'datas': data})
    
def insert(request,username):
    if request.method == 'POST':
        data = plan.objects.create(plan=request.POST['plan'],user_ID=username)
        data.save()
    print(username);
    return redirect('/planner/home/'+username)


def create_plans(request,username,plan_id):

    Subjects = Subject_plan.objects.all()
    plans = Create_plan.objects.filter(Username = username , plan_no = plan_id).order_by('Time_start')
    plan_name = plan.objects.filter(user_ID = username , id = plan_id)
    

    return render(request, 'planners/planner/plan.html',{'Subject': Subjects,'plan_id':plan_id,'user': username ,'plan_data':plans,'plan_name':plan_name})

def delete_plan(request,username,plan_id):
    plan_de =  plan.objects.filter(user_ID = username , id = plan_id).delete()
    Create_plan_de = Create_plan.objects.filter(Username = username , plan_no = plan_id).delete()
    return redirect('/planner/home/'+username)


def inser_plan(request):
     if request.method == 'POST':
        print(request.POST['Sub_ject_code'])
        print(request.POST['user'])
        print(request.POST['day_id'])
        print(request.POST['start_class'])
        print(request.POST['end_class'])
        print(request.POST['plan_id'])
         
        data_plan = Create_plan.objects.create(Subject_ID = Subject_plan.objects.get(Subject_ID = request.POST['Sub_ject_code']),Username = request.POST['user'], day_id = request.POST['day_id'],Time_start = request.POST['start_class'],Time_close = request.POST['end_class'],plan_no = request.POST['plan_id'])
        data_plan.save()
        
     return redirect('create_plans/'+request.POST['user']+'/'+request.POST['plan_id'])   



    

student/views.py
from django.shortcuts import render
from .forms import Profile_form , History_form
from student.models import Student , History
from django.contrib.auth.decorators import login_required 
from django.contrib.auth import get_user_model
from django.contrib import messages


IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg']

@login_required 
def Index(request):
    return render(request, 'students/student/base.html',)


@login_required 
def Profile(request):
    student =Student.objects.filter(student_id=request.user).values()
    form = Profile_form()
    context = {"form": form, 
            'student': student
            }

    if request.method == 'POST':
        form = Profile_form(request.POST, request.FILES)
        if form.is_valid():
            user_pr = form.save(commit=False)
            user_pr.save()
            messages.success(request, f"Profild already in as {user_pr}")
            return render(request, 'students/student/profile.html', {'form': form, 'user_pr': user_pr})
    else:
        print('no post')

    return render(request, 'students/student/profile.html', context)

@login_required 
def SHistory(request):
    H = History.objects.filter(studentid=request.user).values()
    context = {
               "H" : H
            }
    return render(request, 'students/student/history.html',context)



def Planner(request):
    return render(request, 'students/student/planner.html',)


def Plannerco(request):
    return render(request, 'students/student/plannerco.html',)


def Planned(request):
    return render(request, 'students/student/planned.html')

student/templates/students/student/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}">
    
    

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <title>ระบบวางแผนการเรียนของนิสิต</title> 
            
    <div class="jumbotron" id="student_jumbotron">
        <h1 class="display-4">ระบบวางแผนการเรียนสำหรับนิสิต
                              {% include 'myproject/includes/navbaritems.html' %}
                              {% include 'myproject/includes/messaging.html' %}
        </h1>
                    <p class="lead">Study Planner Program For Students</p>
                        <hr class="my-4">
                            <div>
                                      
                                      <a class="btn btn-primary btn-lg" href="{% url 'student:Profile' %}" role="button">ข้อมูลทั่วไปของนิสิต</a>  
                                                  
                                      
                                      <div class="btn-group">
                                                                    <button type="button" class="btn btn-lg btn-warning">ระบบนิสิต</button>
                                                                    <button type="button" class="btn btn-lg btn-warning dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"></button>
                                                  <div class="dropdown-menu">
                                                                    <a class="dropdown-item" href="{% url 'student:Planner' %}">แผนการเรียนตามหลักสูตร</a>
                                                                    <a class="dropdown-item" href="{% url 'student:History' %}">ประวัติการเรียนของนิสิต</a>
                                                                    
                                                  </div>
                                      </div>
                                      <div class="btn-group">
                                                                    <button type="button" class="btn btn-lg btn-success">ระบบวางแผนการเรียน</button>
                                                                    <button type="button" class="btn btn-lg btn-success dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"></button>
                                                  <div class="dropdown-menu">
                                                                    <a class="dropdown-item" href="{% url 'planner:home' user.username %}">วางแผนการเรียน</a>
                                                                    <a class="dropdown-item" href="{% url 'planner:gradepredic' %}">คำนวนเกรดล่วงหน้า</a>
                                                                    <a class="dropdown-item" href="{% url 'planner:subjectall' %}">รายวิชาทั้งหมด</a>
                                                  </div>
                                      </div>
                                      
                          </div>
    </div>   
    </head>
    
    <body>
 

            {% block content %}
            {% block script %}

            {% endblock %}
            {% endblock %}


  </body>
</html>

student/templates/students/student/edit_profile.html
{% extends "students/student/base.html" %}

{% block content %}
    

<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#"><h3>ข้อมูลทั่วไปของนิสิต</h3></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <!--
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        -->
      </ul>
     </div>
  </nav>
   
  <table class="table table-bordered ">
  <thead>
        <tr>
          <th>ข้อมูล</th>
          <th>ข้อมูลทั่วไปของนิสิต</th>
        </tr>
  </thead>

  {% for a in student %}
  <!--<tr>
      <th>Picture</th>
      <td>{{ a.student_picture }}</td></tr>
  <tr>-->
      <th >รหัสประจำตัวนิสิต</th>
      <td>{{ a.student_id }}</td>
  <tr>
      <th >ชื่อ</th>
      <td>{{ a.student_name}}</td></tr>
  <tr>
      <th >นามสกุล</th>
      <td>{{ a.student_surname }}</td></tr>
  <tr>
      <th >ปีที่เข้าศึกษา</th>
      <td>{{ a.student_year}}</td></tr>
  <tr>
      <th >GPA</th>
      <td>{{ a.student_gpa }}</td></tr>
  <tr>
      <th >Email</th>
      <td>{{ a.student_email}}</td></tr>
  
  

 {% endfor %} 
  </table>  

   

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <a class="navbar-brand" href="#"><h3>กรอกข้อมูลของนิสิต</h3></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  </nav>
    
    <form method="POST">
    {% csrf_token %}
    <div class="form-row">
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">รหัสประจำตัวนิสิต</span></div>
                                        {{form.student_id}} 
            </div>   
        </div>
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">ชื่อ</span></div>
                                        {{form.student_name}}  
            </div>   
        </div>
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">นามสกุล</span></div>
                                        {{form.student_surname}} 
            </div>   
        </div>
    </div>                                      
    <div class="form-row">
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">รหัสผ่าน</span></div>
                                        {{form.student_password}} 
            </div>   
        </div>
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">ปีที่เข้าศึกษา</span></div>
                                        {{form.student_year}}  
            </div>   
        </div>
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">GPA</span></div>
                                        {{form.student_gpa}} 
            </div>   
        </div>
    </div>  
    <div class="form-row">
        <div class="col-md-4 mb-3"><div class="input-group">
            <div class="input-group-prepend"><span class="input-group-text">Email</span></div>
                                        {{form.student_email}} 
            </div>   
        </div>
       
        <!--
        <div class="col-md-4 mb-3">
            <div class="input-group-prepend">
            </div>
            <div class="custom-file">
                {{form.student_picture}} 
              <label class="custom-file-label" >Choose Your Picture</label>
            </div>
          </div>
        -->  
    </div>  
    
    <br>
    <center><button type="submit" class="btn btn-primary btn-lg " value="" style="float: center;">บันทึก</button></center>
    
  </form>

	
	



{% endblock content %}

student/templates/students/student/planned.html
{% extends "students/student/base.html" %}
{% block content %}

<nav class="navbar navbar-expand-lg navbar-dark bg-warning">
  <a class="navbar-brand" href="#"><h3>แผนการเรียนที่ออกแบบไว้</h3></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <!--
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      -->
    </ul>
   </div>
</nav>

{% endblock content %}