myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path("register/", views.register, name="register"),
    path("logout", views.logout_request, name="logout"),
    path("login", views.login_request, name="login"),
    path('student/', include('student.urls')),
    path('planner/', include('planner.urls')),
    path("", views.Homepage, name="homepage"),

]

planner/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from myproject import settings
from django.conf.urls.static import static

app_name = 'planner'

urlpatterns = [
    
    path('subjectall', views.planner_subjectall, name='subjectall'),
    path('planning', views.planner_planning, name='planning'),
    path('plan-form', views.planner_form, name='plan-form'),
    path('gradepredic', views.gradepredic, name='gradepredic'),
    url(r'^insert/(?P<username>\w+)/$', views.insert, name='insert'),
    #url(r'insert$', views.insert, name='insert'),
    url(r'inser_plan', views.inser_plan, name='inser_plan'),
    url(r'^create_plans/(?P<username>\w+)/(?P<plan_id>\w+)/$', views.create_plans, name='create_plans'),
    url(r'^delete_plan/(?P<username>\w+)/(?P<plan_id>\w+)/$', views.delete_plan, name='delete_plan'),
    url(r'^home/(?P<username>\w+)/$', views.home, name="home"),
   
]

student/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views
from myproject import settings
from django.conf.urls.static import static

app_name = 'student'

urlpatterns = [
    path('', views.Index, name='Index'),
    path('Planner', views.Planner, name='Planner'),
    path('Plannerco', views.Plannerco, name='Plannerco'),
    path('Planned', views.Planned, name='Planned'),
    path('History', views.SHistory, name ='History'),
    path('Profile', views.Profile, name='Profile'),
  
]

planner/models.py
from django.db import models
from student.models import Student
from django.urls import reverse


# Create your models here.


class Planner(models.Model):
    plan_id = models.IntegerField(primary_key=True)
    student_id = models.ForeignKey(
        Student, on_delete=models.CASCADE, default=None)
    plan_name = models.CharField(max_length=255, default=None)
    plan_year = models.IntegerField()
    plan_semester = models.IntegerField()
    plan_gps = models.FloatField()
    plan_no = models.IntegerField()
    plan_totalcredit = models.IntegerField()
    plan_remark = models.CharField(max_length=500)


class Category(models.Model):
    CategoryID = models.CharField(max_length=1)
    CategoryNAme = models.CharField(max_length=50)
    Category_credit = models.CharField(max_length=3)
    CreateTime = models.DateTimeField('date create')
    CreateBy = models.CharField(max_length=150)
    UpdateTime = models.DateTimeField('date update')
    UpdateBy = models.CharField(max_length=150)


class SubjectGroup(models.Model):
    SubjectGroupID = models.CharField(primary_key=True, max_length=2)
    SubjectGroupName = models.CharField(max_length=250)
    Credit = models.IntegerField()
    CreateTime = models.DateTimeField('date create')
    CreateBy = models.CharField(max_length=150)
    UpdateTime = models.DateTimeField('date update')
    UpdateBy = models.CharField(max_length=150)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None)

class Subject(models.Model):
    subject_id = models.CharField(primary_key=True, max_length=5)
    subject_code = models.CharField(max_length=8)
    subject_nameTH = models.CharField(max_length=100)
    subject_nameEN = models.CharField(max_length=100)
    #subject_detail = models.TextField(max_length=500, default=None)
    subject_credit = models.IntegerField()
    is_have_pre_subject = models.BooleanField(default=None)
    subjectgroup = models.ForeignKey(SubjectGroup, on_delete=models.CASCADE, default=None)

class PreSubject(models.Model):
    subject_id = models.ForeignKey(Subject, on_delete=models.CASCADE)
    pre_subject_id = models.IntegerField()

class SubjectActive(models.Model):
    SA_year = models.CharField(max_length=4)
    SA_semster = models.CharField(max_length=50)
    SA_id = models.CharField(max_length=8)
    SA_nameTH = models.CharField(max_length=100)
    SA_nameEN = models.CharField(max_length=100)
    SA_credit = models.CharField(max_length=1)
    SA_hour= models.CharField(max_length=1)

class addsubject(models.Model):
    subject = models.CharField(max_length=50)
    credit = models.CharField(max_length=1)
    addsubject_date = models.CharField(max_length=10)
    addsubject_startime = models.TimeField(auto_now=False, auto_now_add=False)
    addsubject_endtime = models.TimeField(auto_now=False, auto_now_add=False)
    #addsubject_hours = models.DurationField()
    #def get_time_diff(self):
         #addsubject_hours = addsubject_hours = addsubject_endtime - self.addsubject_startime
         #print (addsubject_hours)
         #return addsubject_hours


class plan(models.Model):
    plan = models.CharField(max_length=200)
    user_ID = models.CharField(max_length=200)

    def __str__(self):
        return "%s %s" % (self.plan, self.user_ID)

class Subject_plan(models.Model):
      Subject_ID = models.CharField(max_length=8,default=0)
      Subject_name = models.CharField(max_length=200)
      Subject_credit = models.IntegerField(default=0)
      group = models.IntegerField(default=0)

class Create_plan(models.Model):
      Subject_ID = models.ForeignKey(Subject_plan,on_delete=models.CASCADE, null=True, blank=True)
      plan_no = models.IntegerField(default=0)
      Time_start = models.TimeField(blank=True, null=True) 
      Time_close = models.TimeField(blank=True, null=True)
      day_id = models.IntegerField(default=0)
      Username = models.CharField(max_length=200,default=0)

    

planner/forms.py
from django import forms
from .models import addsubject ,Planner 



class addsubject_form(forms.ModelForm):
    subject = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    credit = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    addsubject_date = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control' }))
    addsubject_startime = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    addsubject_endtime = forms.TimeField(widget=forms.TimeInput(format='%H:%M'))
    #addsubject_hours = forms.DurationField()
    
    class Meta:
        model = addsubject 
        fields = [
			'subject',
            'credit',
            'addsubject_date',
            'addsubject_startime',
			'addsubject_endtime', 
        ]

planner/views.py
from django.shortcuts import render, redirect
from planner.models import Subject, SubjectGroup, PreSubject, Category,addsubject,Subject_plan
from student.models import History 
from .forms import addsubject_form
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from planner.models import plan
from planner.models import Subject_plan
from planner.models import Create_plan
from django.db.models import Sum
from django.db.models import Count

def planner_subjectall(request):
    s = Subject.objects.filter()
    sg = SubjectGroup.objects.filter()
    ps = PreSubject.objects.filter()
    c = Category.objects.filter()

    context = {
        's': s,
        'sg': sg,
        'ps': ps,
        'c': c
    }

    return render(request, 'planners/planner/planner_subjectall.html', context)
    

def planner_planning(request):
    add_sj = addsubject.objects.filter()
    context ={
        'add_sj' : add_sj
    }
    return render(request, 'planners/planner/planner_planning.html', context)


@login_required 
def planner_form(request):
    P = addsubject.objects.filter()
    form = addsubject_form()
    context = {
                
                'form' : form,
                'P' : P  
            }
    if request.method == 'POST':
        form = addsubject_form(request.POST, request.FILES)
        
        if form.is_valid():
            user_pr = form.save(commit=False)
            user_pr.save()
            messages.success(request, f"เพิ่มวิชาเรียบร้อยแล้ว")
            return render(request, 'planners/planner/planner_form.html', {'form': form, 'user_pr': user_pr})
    else:
        print('no post')
            
    return render(request, 'planners/planner/planner_form.html',context)

def gradepredic(request):
    Ss = Subject_plan.objects.filter()
    H = History.objects.filter(studentid=request.user).values()
    context = {
                
                'Ss' : Ss,
                'H' : H  
            }
    return render(request, 'planners/planner/grade_predic.html',context)
    


#**************************************************************************************
def home(request,username):
    data = plan.objects.filter(user_ID = username)
    if not data :
        return render(request, 'planners/planner/home.html')
    else:
        return render(request, 'planners/planner/home.html',{'datas': data})
    
def insert(request,username):
    if request.method == 'POST':
        data = plan.objects.create(plan=request.POST['plan'],user_ID=username)
        data.save()
    print(username);
    return redirect('/planner/home/'+username)


def create_plans(request,username,plan_id):

    Subjects = Subject_plan.objects.all()
    plans = Create_plan.objects.filter(Username = username , plan_no = plan_id).order_by('Time_start')
    plan_name = plan.objects.filter(user_ID = username , id = plan_id)
    

    return render(request, 'planners/planner/plan.html',{'Subject': Subjects,'plan_id':plan_id,'user': username ,'plan_data':plans,'plan_name':plan_name})

def delete_plan(request,username,plan_id):
    plan_de =  plan.objects.filter(user_ID = username , id = plan_id).delete()
    Create_plan_de = Create_plan.objects.filter(Username = username , plan_no = plan_id).delete()
    return redirect('/planner/home/'+username)


def inser_plan(request):
     if request.method == 'POST':
        print(request.POST['Sub_ject_code'])
        print(request.POST['user'])
        print(request.POST['day_id'])
        print(request.POST['start_class'])
        print(request.POST['end_class'])
        print(request.POST['plan_id'])
         
        data_plan = Create_plan.objects.create(Subject_ID = Subject_plan.objects.get(Subject_ID = request.POST['Sub_ject_code']),Username = request.POST['user'], day_id = request.POST['day_id'],Time_start = request.POST['start_class'],Time_close = request.POST['end_class'],plan_no = request.POST['plan_id'])
        data_plan.save()
        
     return redirect('create_plans/'+request.POST['user']+'/'+request.POST['plan_id'])   



    

planner/templates/planners/planner/home.html
{% extends "planners/planner/planner_base.html" %}
{% block content %}
    <!-- Button trigger modal -->

<div class="row align-self-center"><div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
  <h3 class="text-center mb-3">วางแผนการเรียน : Overview</h3>
  <div class="card mb-3">
    <div class="card-body">
        <script> 
            var i = 0;
        </script>
    {% for data in datas %} 
      <script> 
            i++;
        </script>
      <div class="row">
      <div class="col-sm text-center mt-2 font-weight-bold" style="vertical-align: middle;"><script>document.write(i);</script></div>
        <div class="col-sm text-center m-2">{{data.plan}}</div>
        <div class="col-sm text-center m-2"><a class="btn btn-outline-info" href="/planner/create_plans/{{data.user_ID}}/{{data.id}}">view</a></div>
      <div class="col-sm text-center"><button type="button" class="btn btn-danger" onclick = "window.location.href = '/planner/delete_plan/{{data.user_ID}}/{{data.id}}'">ลบ</button></div>
    </div>
    {% endfor %}
          <div class="css_rp" align ="center"><button type="button" id = "btn1" class="btn btn-success"  data-toggle="modal" data-target="#exampleModal">เพิ่มแผน </button></div>
  </div>
</div>
        
          
          </div>
          <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
             <div class="alert alert-success" role="alert"><h5 class="alert-heading font-weight-bold">คู่มือการใช้งาน</h5>
                  <hr>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>เมื่อต้องการสร้างแผนการเรียนใหม่ </h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>1. ให้กดเพิ่มแผนการเรียน </h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>2. ระบบจะแสดงหน้าต่างสอบถามการสร้างแผนการเรียน</h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>3. ถ้ายังไม่มีแผนการเรียนให้เลือก สร้างแผนการเรียนใหม่ ใส่ชื่อแผนการเรียน</h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>4. จะได้ตารางมาหนึ่งตาราง</h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]"><div class="btn-toolbar justify-content-between align-items-center">
                    <h6>5. เพิ่มรายวิชาที่ต้องการออกแบบ </h6>
                    <span></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
       </div>   
  <!-- Modal -->
  

   
      <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">เพิ่มแผนตารางเรียน</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              
              <form action="{% url 'planner:insert' user.username %}" method="post">{% csrf_token %}
                <div class="form-group">
                  <label for="text" class="col-form-label">ชื่อแผน:</label>
                  <input type="text" class="form-control" id="plan-name"  name="plan"> 
                </div>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </form>
          </div>
        </div>
      </div>

{% endblock %}

planner/templates/planners/planner/planner_base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet"  href="{% static 'css/style.css' %}">
    <link rel="stylesheet"  href="{% static 'scss/style.scss' %}">

    <!--<link rel="stylesheet"  href="{% static 'css/jquery.dataTables.min.css' %}">-->
    <link rel="stylesheet" type="text/css" href="{% static 'css.css' %}">
    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <script src="{% static 'js/jquery-3.4.1.js' %}"></script>
    <title>ระบบวางแผนการเรียนของนิสิต</title> 
            
    <div class="jumbotron" id="planning_jumbotron">
        <h1 class="display-4">ระบบวางแผนการเรียนสำหรับนิสิต
                              {% include 'myproject/includes/navbaritems.html' %}
                              {% include 'myproject/includes/messaging.html' %}
        </h1>
                    <p class="lead">Study Planner Program For Students</p>
                        <hr class="my-4">
                            <div>
                                      
                                      <a class="btn btn-primary btn-lg" href="{% url 'student:Profile' %}" role="button">ข้อมูลทั่วไปของนิสิต</a>  
                                                  
                                      
                                      <div class="btn-group">
                                                                    <button type="button" class="btn btn-lg btn-warning">ระบบนิสิต</button>
                                                                    <button type="button" class="btn btn-lg btn-warning dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"></button>
                                                  <div class="dropdown-menu">
                                                                    <a class="dropdown-item" href="{% url 'student:Planner' %}">แผนการเรียนตามหลักสูตร</a>
                                                                    <a class="dropdown-item" href="{% url 'student:History' %}">ประวัติการเรียนของนิสิต</a>
                                                                    
                                                  </div>
                                      </div>
                                      <div class="btn-group">
                                                                    <button type="button" class="btn btn-lg btn-success">ระบบวางแผนการเรียน</button>
                                                                    <button type="button" class="btn btn-lg btn-success dropdown-toggle dropdown-toggle-split" data-toggle="dropdown"></button>
                                                  <div class="dropdown-menu">
                                                                    <a class="dropdown-item" href="{% url 'student:Planner' %}">หน้าหลัก</a>
                                                                    <a class="dropdown-item" href="{% url 'planner:gradepredic' %}">คำนวนเกรดล่วงหน้า</a>
                                                                    <a class="dropdown-item" href="{% url 'planner:subjectall' %}">รายวิชาทั้งหมด</a>
                                                   </div>
                                      </div>
                                      
                          </div>
    </div>   
    </head>

    <body>
 
           
            {% block content %}
            {% block script %}

            {% endblock %}
            {% endblock %}

<script src="{% static 'js.js' %}"></script> 
  </body>
</html>

planner/templates/planners/planner/planner_form.html
{% extends "planners/planner/planner_base.html" %}
{% block content %}
<nav class="navbar navbar-expand-lg navbar-dark bg-warning ">
    <a class="navbar-brand text-dark" href="#"><h3>วางแผนการเรียน</h3></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
      </ul>
     </div>
</nav>

<!--ระบบวางแผน-->
<table class="table table-responsive-sm table-responsive-md table-responsive-lg table-bordered text-center animated fadeIn" style="font-size: 1.7ex;">
  <thead>
    <tr>
      <th scope="col"></th>
      <th colspan="2" scope="col">8:00</th>
      <th colspan="2" scope="col">9:00</th>
      <th colspan="2" scope="col">10:00-</th>
      <th colspan="2" scope="col">11:00-</th>
      <th class="table-active" colspan="2" scope="col">12:00-13:00</th>
      <th colspan="2" scope="col">13:00</th>
      <th colspan="2" scope="col">14:00</th>
      <th colspan="2" scope="col">15:00</th>
      <th colspan="2" scope="col">16:00</th>
      <th colspan="2" scope="col">17:00</th>
      <th colspan="2" scope="col">18:00</th>
      <th colspan="2" scope="col">19:00</th>
      <th colspan="2" scope="col">20:00-</th>
      
      <tr>
        <th scope="col"></th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
        <th colspan="1" scope="col">00</th>
        <th colspan="1" scope="col">30</th>
      </tr>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">M</th>
      <td colspan="4">่สา่ส่ส่ส่ส่</td></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
    </tr>
    <tr>
      <th scope="row">T</th>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
    </tr>
    <tr>
      <th scope="row">W</th>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
    </tr>
    <tr>
      <th scope="row">T</th>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
    </tr>
    <tr>
      <th scope="row">F</th>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
      <td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td><td colspan="2"></td>
    </tr>

  </tbody>
</table>
<div class="btn-group mr-2">
  <button type="button" class="btn btn-sm btn-outline-danger float-right font-weight-bold">Delete</button>
  <button type="button" class="btn btn-sm btn-outline-info font-weight-bold">Reset</button>
</div>
<button type="button" class="btn btn-outline-dark float-right mb-3 ml-3" data-toggle="modal" data-target="#exampleModalCenter">เพิ่มรายวิชา (กำหนดเอง)</button>
<a  class="btn btn-outline-success float-right mb-3 ml-3"  href="{% url 'planner:planning' %}">OVERVIEW</a>       

{% include "planners/planner/planner_modal_form.html" %}  
{% endblock content %}
{% block javascript %}
<script type="text/javascript">
</script>
{% endblock javascript %}

planner/templates/planners/planner/planner_planning.html
{% extends "planners/planner/planner_base.html" %}
{% block content %}
<button type="button" class="btn btn-outline-dark float-right mb-3 ml-3" data-toggle="modal" data-target="#exampleModalCenter">เพิ่มแผนการเรียน</button>
<div class="row align-self-center"><div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
  <h3 class="text-center mb-3">Overview</h3>
  <div class="card mb-3">
    <div class="card-body">
      <div class="row">
      <div class="col-sm text-center mt-2 font-weight-bold" style="vertical-align: middle;">1</div>
        <div class="col-sm text-center m-2">3 รายวิชา</div><div class="col-sm text-center m-2">4 หน่วยกิต</div>
      <div class="col-sm text-center"><a class="btn btn-light btn-block " href="{% url 'planner:plan-form' %}">View</a></div>
    </div>
  </div>
</div>
        
          
          </div>
          <div class="col-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
             <div class="alert alert-success" role="alert"><h5 class="alert-heading font-weight-bold">คู่มือการใช้งาน</h5>
                  <hr>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>เมื่อต้องการสร้างแผนการเรียนใหม่ </h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>1. ให้กดเพิ่มแผนการเรียน </h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>2. ระบบจะแสดงหน้าต่างสอบถามการสร้างแผนการเรียน</h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>3. ถ้ายังไม่มีแผนการเรียนให้เลือก สร้างแผนการเรียนใหม่ ใส่ชื่อแผนการเรียน</h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]">
                    <div class="btn-toolbar justify-content-between align-items-center">
                      <h6>4. จะได้ตารางมาหนึ่งตาราง</h6>
                      <span></span>
                    </div>
                  </div>
                  <div styles="[object Object]"><div class="btn-toolbar justify-content-between align-items-center">
                    <h6>5. เพิ่มรายวิชาที่ต้องการออกแบบ </h6>
                    <span></span>
                  </div>
                </div>
              </div>
            </div>
          </div>
       </div>   
         
{% include "planners/planner/planner_table.html" %} 
{% include "planners/planner/planner_option.html" %}  
{% endblock content %}
{% block javascript %}
<script type="text/javascript">


</script>
{% endblock javascript %}

planner/templates/planners/planner/planner_table.html
<!--table-->
<table class="table table-bordered bg-warinig">
  <thead>
    <tr>
      <th scope="col">รหัสวิชา</th>
      <th scope="col">หน่วยกิต</th>  
      <th scope="col">วันที่เรียน</th>
      <th scope="col">เริ่มเรียน</th>
      <th scope="col">ถึง</th>
     </tr>
  </thead>
  <tbody>
      {% for a in add_sj %}
      <tr>   
        <td>{{ a.subject}}</td>
        <td>{{ a.credit}}</td>
        <td>{{ a.addsubject_date }}</td>
        <td>{{ a.addsubject_startime }}</td>
        <td>{{ a.addsubject_endtime }}</td>
      </tr>
      {% endfor%}
    </tbody>
  </table>